title: Iceland Tourism Directory
description: Curated directory of Iceland travel tools and resources
baseurl: ""
url: ""

#theme: lanyon (sidebar theme with dark mode)

remote_theme: poole/lanyon

# Lanyon theme settings
tagline: 'Essential tourism resources maintained by locals'
author:
  name: 'Local Iceland Guide'
  url: https://github.com/ironmaster16

# Sidebar settings
sidebar_home_link: true

# Optional: Social links in footer
github_username: ironmaster16

# Collections for organizing content (optional - can add later)
# collections:
#   resources:
#     output: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme # add this line to the plugins list if you already have one