title: Iceland Tourism Directory
description: Curated directory of Iceland travel tools and resources
baseurl: ""
url: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale: "en-US"
name: "Iceland Tourism Directory"
repository: "ironmaster16/ironmaster16.github.io"

# Site Author
author:
  name: "Local Iceland Guide"
  bio: "Essential tourism resources maintained by locals"
  location: "Iceland"

# Reading Files
include:
  - _pages

# Exclude from processing
exclude:
  - docs/
  - README.md

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "resources"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap