title: Iceland Tourism Directory
description: Curated directory of Iceland travel tools and resources
baseurl: ""
url: ""

#theme: slate (dark version of cayman)

remote_theme: pages-themes/slate@v0.2.0

# Optional: Social links in footer
github_username: ironmaster16

# Collections for organizing content (optional - can add later)
# collections:
#   resources:
#     output: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme # add this line to the plugins list if you already have one